# -*- coding: utf-8 -*-
"""Negative Picture.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zgKRJ8i3YxC_C2Nukg6PQssDVvpj_Cyb

Alfrethanov Christian Wijaya
24060120140147
Kelas A
Tugas Grafika dan Komputasi Visual
'Gambar dengan Efek Negatif'
"""

from google.colab import drive

drive.mount("/content/drive")

import cv2
import matplotlib.pyplot as plt

Path = '/content/drive/MyDrive/Photos/Photoshoot.jpg'

Img = cv2.imread(Path, 1)
Img_Gray = cv2.imread(Path, 0)

Img = cv2.cvtColor(Img, cv2.COLOR_BGR2RGB)
Img_Gray = cv2.cvtColor(Img, cv2.COLOR_BGR2GRAY)

Negative_Colour = abs(255-Img)
Negative_Gray = abs(255-Img_Gray)

Images = [Img, Img_Gray, Negative_Colour, Negative_Gray]
Title = ['Coloured', 'Gray', 'Negative Colour', 'Negative Gray']


plt.subplot(2, 2, 1)
plt.title(Title[0]) #Title = 'Coloured'
plt.imshow(Images[0]) #Images = Img
plt.xticks([])
plt.yticks([])

plt.subplot(2, 2, 2)
plt.title(Title[1]) #Title = 'Gray'
plt.imshow(Images[1], cmap='gray') #Images = Img_Gray
plt.xticks([])
plt.yticks([])

plt.subplot(2, 2, 3)
plt.title(Title[2]) #Title = 'Negative Colour'
plt.imshow(Images[2]) #Images = Negative_Colour
plt.xticks([])
plt.yticks([])

plt.subplot(2, 2, 4)
plt.title(Title[3]) #Title = 'Negative Gray'
plt.imshow(Images[3], cmap='gray') #Images = Negative_Gray
plt.xticks([])
plt.yticks([])

plt.show()